Implement pyze functionnality
hacf-fr/renault-api pull request #18
Opened 2020-11-07 21:14 UTC by epenet

Add a proxy over pyze gigya/kamereon/vehicle objects

2020-11-07 21:16 UTC, epenet commented
@oncleben31 / @Quentame 
Il faut encore que j'ajoute tous les tests, mais que pensez-vous de cette structure?

2020-11-08 22:06 UTC, epenet commented on src/renault_api/renault_account.py
> +        self._kamereon: Kamereon = copy.deepcopy(kamereon)
I have refactored this by creating a KamereonOverride class (set_account_id/get_account_id are now only in memory)

2020-11-08 22:09 UTC, epenet commented on src/renault_api/renault_account.py
> +    def get_vehicles(self) -> Any:
I am open to suggestions for naming convention.
For now, I have tried to keep the method names from PyZE, and only added:
- RenaultClient.get_account(account_id)
- RenaultAccount.get_vehicle(vin)

2020-11-08 22:11 UTC, epenet commented on src/renault_api/renault_vehicle.py
> +    def battery_status(self) -> Any:
For now, I considered that all the return from PyZE are unreliable.

2020-11-08 22:11 UTC, epenet commented on pyproject.toml
> +version = "0.0.1-alpha.1"
Removed from PR

2020-11-10 15:21 UTC, epenet commented
@oncleben31 / @Quentame

Ca y est, j'ai ajouté les fonctions pyze, ainsi que tous les tests associés.
Il faudrait arriver à définir maintenan't s'il vaut mieux:
- garder les noms de "pyze"
- utiliser les noms de l'api Renault
- définir de nouveaux noms

Là avec pyze il y a des incohérences, par exemple:
- hvac_history() fait un GET sur /hvac-sessions
- hvac_statistics() fait un GET sur /hvac-history

2020-11-10 15:32 UTC, epenet commented
Et aussi comment au mieux différencier ce qui est "création d'objet" de ce qui est "appel REST".
Est-ce utile de garder par exemple:
- get_accounts_raw() => l'appel à pyze
- get_account(xxx) => création d'un objet RenaultAccount
- get_accounts() => création d'une liste de RenaultAccount

2020-11-11 17:32 UTC, Quentame commented
> Il faudrait arriver à définir maintenant s'il vaut mieux:
> 
> * garder les noms de "pyze"
> * utiliser les noms de l'api Renault
> * définir de nouveaux noms

Les noms des fonctions ?
Si ça t'arrange n'hésite pas à renommer, voir se rapprocher des noms de l'API Renault me parais bien 👍 

PS: je n'ai pas encore lu la PR, je mettrais à jour mon commentaire après si utile.

2020-11-11 19:15 UTC, Quentame reviewed
Should we add PyZE as a dependency or being totally independent ?

I think we better be independent.

(review not finished)

2020-11-11 23:25 UTC, Quentame requested changes
I think we should drop PyZE dependency to improve reliability (with less `Any` type), drop potential issue from the lib and be easier to maintain.

For naming convention, I would say: `[get/set]_[theme](_[precision])`
Exemples:
- GET
  - `get_account() -> Account[]`
  - `get_vehicles() -> Vehicle[]`
  - `get_vehicles_vin() -> str[]`
  - `get_vehicle(vin: str) -> Vehicle`
  - `get_vehicle_location(vin: str) -> (str, str)`
  - `get_location() -> (str, str)`
  - `get_ mileage() -> int`
- SET
  - `set_ac_start(temp: int, when: Optional[datetime] = None) -> bool?`
  - `set_ac_stop() -> bool?`
  - `set_charge_start() -> bool?`
  - `set_charge_mode(self, charge_mode: ChargeMode) -> bool?`
  -  `set_charge_schedules(self, schedules: ChargeSchedules) ->  bool?`

2020-11-11 23:25 UTC, Quentame commented on src/renault_api/renault_vehicle.py
> +        """Get vehicle hvac-status."""
```suggestion
        """Get vehicle charge mode."""
```

2020-11-11 23:25 UTC, Quentame commented on src/renault_api/renault_vehicle.py
> +        return self._vehicle.ac_start(when, temperature)
I don't think the temperature should be optional.

2020-11-11 23:25 UTC, Quentame commented on src/renault_api/renault_vehicle.py
> +        """Start vehicle charge."""
```suggestion
        """Stop vehicle air-conditioning."""
```

2020-11-11 23:25 UTC, Quentame commented on src/renault_api/renault_vehicle.py
> +    def cancel_ac(self) -> Any:
```suggestion
    def ac_stop(self) -> Any:
```
?

2020-11-11 23:25 UTC, Quentame commented on src/renault_api/renault_vehicle.py
> +        """Start vehicle charge."""
```suggestion
        """Start vehicle air-conditioning."""
```

2020-11-11 23:25 UTC, Quentame commented on src/renault_api/renault_vehicle.py
> +        """Start vehicle charge."""
```suggestion
        """Start vehicle charge schedule."""
```

2020-11-11 23:25 UTC, Quentame commented on src/renault_api/renault_vehicle.py
> +        """Get vehicle cockpit data."""
```suggestion
        """Get vehicle mileage."""
```

2020-11-24 16:37 UTC, closed without merging