Implement pyze functionnality (v2)
hacf-fr/renault-api pull request #23
Opened 2020-11-12 20:55 UTC by epenet

2020-11-13 19:26 UTC, epenet commented
This PR is too big => converted to draft

2020-11-18 11:25 UTC, Quentame requested changes
Some typing, otherwise LGTM

2020-11-18 11:25 UTC, Quentame commented on src/renault_api/renault_client.py
> +from . import renault_account
```suggestion
from .renault_account import RenaultAccount
```

2020-11-18 11:25 UTC, Quentame commented on src/renault_api/renault_client.py
> +from . import gigya
```suggestion
from .gigya import Gigya
```

2020-11-24 09:37 UTC, closed without merging