Pin aiohttp to 3.7.1 to match HA
hacf-fr/renault-api pull request #29
Opened 2020-11-13 20:25 UTC by epenet

https://github.com/home-assistant/core/blob/dev/requirements.txt

2020-11-13 20:27 UTC, epenet commented
@Quentame this is linked to #20
Since HA has got it pinned to 3.7.1, is it not better to keep it as 3.7.1 until HA bumps it also?

2020-11-18 11:30 UTC, Quentame requested changes
I think you better propose HA to bump to 3.7.2 :relieved: 

For a major or minor I would say yes, but it's a fix version.

2020-11-18 12:00 UTC, epenet commented
Apparently there is a regression: https://github.com/home-assistant/core/pull/42514 in 3.7.2

2020-11-18 14:40 UTC, Quentame approved these changes

2020-11-18 14:41 UTC, merged