Update models.py
hacf-fr/renault-api pull request #452
Opened 2021-12-24 18:25 UTC by ZMan88

It now seems to work for Zoe Phase 2

2021-12-27 09:28 UTC, epenet commented
Do you have some sample results?
Maybe you could add a positive fixture like this, as we only seem to have a negative one currently :
https://github.com/hacf-fr/renault-api/blob/56ad77f7ebd27a567d6a16303a5c17bb7e3f7729/tests/fixtures/kamereon/vehicle_data/hvac-status.json#L1-L7

2021-12-27 10:14 UTC, ZMan88 commented
Ok, 
I will add that, but the response I get from the api is slightly different, it looks like this:
{
    "id": "xxx MY VIN xxx",
    "socThreshold": 40,
    "lastUpdateTime": "2021-12-27T09:37:39Z",
    "hvacStatus": "off"
}
the format that you are expecting is from where?
Thanks, and sorry for the clumsy approach :)

2021-12-27 10:24 UTC, epenet commented
This is still an "off" status. Do you a real fixture with "on" status or does it always show "off" anyway?
On Zoe40, it shows "off" even when hvac is "on".

2021-12-27 10:40 UTC, ZMan88 commented
It shows on when the preconditioning is triggered. Does it need to be set to "on" in the fixture?

2021-12-27 10:42 UTC, epenet commented
Yes, we need to make sure that we have a "real positive" in the fixture.

2021-12-27 11:35 UTC, epenet commented
Are you able to run pytest locally before you push commits?
Unless all tests pass I cannot merge...

2021-12-27 11:59 UTC, ZMan88 commented
I am having some trouble with my dev environment. I will try to fix it and run the tests locally and then push changes

2021-12-27 12:03 UTC, epenet commented
Thanks

2021-12-30 22:11 UTC, epenet reviewed
Please fix these formatting issues

2021-12-30 22:11 UTC, epenet commented on tests/fixtures/kamereon/vehicle_data/hvac-status.zoe_50.json
> +}
Please add the missing carriage return here:
```suggestion
}

```

2021-12-30 22:11 UTC, epenet commented on tests/kamereon/test_kamereon_vehicles.py
> +                "supports-hvac-status": vehicle_details.supports_endpoint("hvac-status"),
Please revert this change, it is causing formatting issues.
```suggestion
                "supports-hvac-status": vehicle_details.supports_endpoint(
                    "hvac-status"
                ),
```

2021-12-30 22:14 UTC, epenet commented
To fix the tests, please ensure that you update the expected output for `zoe_50.1.json` in `tests/cli/test_vehicle.py` (line 100):
```python
    "zoe_50.1.json": (
        "--------------------  -------------------------\n"
        "Battery level         50 %\n"
        "Last updated          2020-11-17 09:06:48\n"
        "Range estimate        128 km\n"
        "Plug state            PlugState.UNPLUGGED\n"
        "Charging state        ChargeState.NOT_IN_CHARGE\n"
        "Charge mode           always\n"
        "Total mileage         49114.27 km\n"
        "GPS Latitude          48.1234567\n"
        "GPS Longitude         11.1234567\n"
        "GPS last updated      2020-02-18 17:58:38\n"
        "HVAC status           off\n"
        "External temperature  8.0 °C\n"
        "--------------------  -------------------------\n"
    ),
```

2021-12-31 08:29 UTC, epenet commented on tests/cli/test_vehicle.py
> +        "HVAC status           on\n"
This still has spacing issues. All the text needs to be aligned.

2022-01-01 20:54 UTC, epenet commented
Please review the formatting issues from https://github.com/hacf-fr/renault-api/runs/4672946801?check_suite_focus=true
And please adjust the tests a little more - GPS should be before HVAC status: https://github.com/hacf-fr/renault-api/runs/4672947004?check_suite_focus=true

2022-01-03 07:22 UTC, epenet commented
We're almost there - there are still some formatting issues.
Could you please adjust?

2022-01-03 08:09 UTC, ZMan88 commented
I will love to but unfortunately I can't figure out what the problems are...
Any pointers?
Also what IDE are u using? I am using VS Code.

2022-01-03 08:10 UTC, epenet commented
If you look at the test details, you will see it simply a missing comma here or there: https://github.com/hacf-fr/renault-api/runs/4685458157?check_suite_focus=true

2022-01-03 13:30 UTC, ZMan88 commented
I'm sorry but I cannot figure out what's wrong 🙈

2022-01-05 08:09 UTC, epenet requested changes
Please fix the pre-commit warnings

2022-01-05 08:09 UTC, epenet commented on src/renault_api/kamereon/models.py
> +    socThreshold: Optional[float]
```suggestion
    socThreshold: Optional[float]  # noqa: N815
```

2022-01-05 08:09 UTC, epenet commented on tests/fixtures.py
> +    inject_get_hvac_status(mocked_responses,vehicle)
```suggestion
    inject_get_hvac_status(mocked_responses, vehicle)
```

2022-01-05 08:09 UTC, epenet commented on tests/test_renault_vehicle.py
> +    fixtures.inject_get_hvac_status(mocked_responses,"zoe")
```suggestion
    fixtures.inject_get_hvac_status(mocked_responses, "zoe")
```

2022-01-05 08:09 UTC, epenet commented on tests/test_renault_vehicle.py
> +    fixtures.inject_get_hvac_status(mocked_responses,"zoe_50")
```suggestion
    fixtures.inject_get_hvac_status(mocked_responses, "zoe_50")
```

2022-01-05 09:32 UTC, epenet commented
You should be able to run `pre-commit run --all-files` to fix the format issues.

2022-01-27 07:58 UTC, epenet commented on tests/fixtures.py
> +        filename = f"hvac-status.{vehicle}.json"
```suggestion
    filename = "hvac-status.1.json"
    if vehicle in "zoe_50":
        filename = f"hvac-status.2.json"
```

2022-01-27 10:36 UTC, merged